[package]
name = "daedalus"
version = "0.1.0"
edition = "2021"

[dependencies]
actix-web = "4"
argon2 = "0.5.2"
chrono = { version = "0.4.31", features = ["serde"] }
derive_more = "0.99.17"
diesel = { version = "2.1.0", features = [
  "chrono",
  "postgres",
  "postgres_backend",
  "r2d2",
  "serde_json",
  "uuid",
] }
diesel_migrations = "2.1.0"
dotenvy = "0.15.7"
serde = { version = "1.0.193", features = ["derive"] }
serde_json = "1.0.108"
