# For documentation on how to configure this file,
# see https://diesel.rs/guides/configuring-diesel-cli
[print_schema]
with_docs = true
file = "src/database/schema.rs"
patch_file = "src/database/schema.patch"