[package]
name = "daedalus-data"
version = "0.1.0"
edition = "2021"

[dependencies]
chrono = "0.4.31"
diesel = { version = "2.1.0", features = [
  "chrono",
  "postgres",
  "postgres_backend",
  "r2d2",
] }
diesel_migrations = "2.1.0"
