// @generated automatically by Diesel CLI.

diesel::table! {
    /// Representation of the `tenants` table.
    ///
    /// (Automatically generated by Diesel.)
    tenants (id) {
        /// The `id` column of the `tenants` table.
        ///
        /// Its SQL type is `Int4`.
        ///
        /// (Automatically generated by Diesel.)
        id -> Int4,
        /// The `name` column of the `tenants` table.
        ///
        /// Its SQL type is `Varchar`.
        ///
        /// (Automatically generated by Diesel.)
        #[max_length = 255]
        name -> Varchar,
        /// The `created_at` column of the `tenants` table.
        ///
        /// Its SQL type is `Timestamptz`.
        ///
        /// (Automatically generated by Diesel.)
        created_at -> Timestamptz,
        /// The `updated_at` column of the `tenants` table.
        ///
        /// Its SQL type is `Timestamptz`.
        ///
        /// (Automatically generated by Diesel.)
        updated_at -> Timestamptz,
        /// The `deleted_at` column of the `tenants` table.
        ///
        /// Its SQL type is `Nullable<Timestamptz>`.
        ///
        /// (Automatically generated by Diesel.)
        deleted_at -> Nullable<Timestamptz>,
    }
}

diesel::table! {
    /// Representation of the `users` table.
    ///
    /// (Automatically generated by Diesel.)
    users (id) {
        /// The `id` column of the `users` table.
        ///
        /// Its SQL type is `Int8`.
        ///
        /// (Automatically generated by Diesel.)
        id -> Int8,
        /// The `tenant_id` column of the `users` table.
        ///
        /// Its SQL type is `Int4`.
        ///
        /// (Automatically generated by Diesel.)
        tenant_id -> Int4,
        /// The `email` column of the `users` table.
        ///
        /// Its SQL type is `Varchar`.
        ///
        /// (Automatically generated by Diesel.)
        #[max_length = 255]
        email -> Varchar,
        /// The `password` column of the `users` table.
        ///
        /// Its SQL type is `Varchar`.
        ///
        /// (Automatically generated by Diesel.)
        #[max_length = 255]
        password -> Varchar,
        /// The `created_at` column of the `users` table.
        ///
        /// Its SQL type is `Timestamptz`.
        ///
        /// (Automatically generated by Diesel.)
        created_at -> Timestamptz,
        /// The `updated_at` column of the `users` table.
        ///
        /// Its SQL type is `Timestamptz`.
        ///
        /// (Automatically generated by Diesel.)
        updated_at -> Timestamptz,
        /// The `deleted_at` column of the `users` table.
        ///
        /// Its SQL type is `Nullable<Timestamptz>`.
        ///
        /// (Automatically generated by Diesel.)
        deleted_at -> Nullable<Timestamptz>,
    }
}

diesel::table! {
    /// Representation of the `workflow_actions` table.
    ///
    /// (Automatically generated by Diesel.)
    workflow_actions (id) {
        /// The `id` column of the `workflow_actions` table.
        ///
        /// Its SQL type is `Uuid`.
        ///
        /// (Automatically generated by Diesel.)
        id -> Uuid,
        /// The `state_id` column of the `workflow_actions` table.
        ///
        /// Its SQL type is `Uuid`.
        ///
        /// (Automatically generated by Diesel.)
        state_id -> Uuid,
        /// The `name` column of the `workflow_actions` table.
        ///
        /// Its SQL type is `Varchar`.
        ///
        /// (Automatically generated by Diesel.)
        #[max_length = 255]
        name -> Varchar,
        /// The `description` column of the `workflow_actions` table.
        ///
        /// Its SQL type is `Nullable<Text>`.
        ///
        /// (Automatically generated by Diesel.)
        description -> Nullable<Text>,
        /// The `timing` column of the `workflow_actions` table.
        ///
        /// Its SQL type is `Varchar`.
        ///
        /// (Automatically generated by Diesel.)
        #[max_length = 255]
        timing -> Varchar,
        /// The `configuration` column of the `workflow_actions` table.
        ///
        /// Its SQL type is `Nullable<Jsonb>`.
        ///
        /// (Automatically generated by Diesel.)
        configuration -> Nullable<Jsonb>,
        /// The `created_at` column of the `workflow_actions` table.
        ///
        /// Its SQL type is `Timestamptz`.
        ///
        /// (Automatically generated by Diesel.)
        created_at -> Timestamptz,
        /// The `updated_at` column of the `workflow_actions` table.
        ///
        /// Its SQL type is `Timestamptz`.
        ///
        /// (Automatically generated by Diesel.)
        updated_at -> Timestamptz,
        /// The `deleted_at` column of the `workflow_actions` table.
        ///
        /// Its SQL type is `Nullable<Timestamptz>`.
        ///
        /// (Automatically generated by Diesel.)
        deleted_at -> Nullable<Timestamptz>,
    }
}

diesel::table! {
    /// Representation of the `workflow_states` table.
    ///
    /// (Automatically generated by Diesel.)
    workflow_states (id) {
        /// The `id` column of the `workflow_states` table.
        ///
        /// Its SQL type is `Uuid`.
        ///
        /// (Automatically generated by Diesel.)
        id -> Uuid,
        /// The `workflow_id` column of the `workflow_states` table.
        ///
        /// Its SQL type is `Uuid`.
        ///
        /// (Automatically generated by Diesel.)
        workflow_id -> Uuid,
        /// The `name` column of the `workflow_states` table.
        ///
        /// Its SQL type is `Varchar`.
        ///
        /// (Automatically generated by Diesel.)
        #[max_length = 255]
        name -> Varchar,
        /// The `description` column of the `workflow_states` table.
        ///
        /// Its SQL type is `Nullable<Text>`.
        ///
        /// (Automatically generated by Diesel.)
        description -> Nullable<Text>,
        /// The `created_at` column of the `workflow_states` table.
        ///
        /// Its SQL type is `Timestamptz`.
        ///
        /// (Automatically generated by Diesel.)
        created_at -> Timestamptz,
        /// The `updated_at` column of the `workflow_states` table.
        ///
        /// Its SQL type is `Timestamptz`.
        ///
        /// (Automatically generated by Diesel.)
        updated_at -> Timestamptz,
        /// The `deleted_at` column of the `workflow_states` table.
        ///
        /// Its SQL type is `Nullable<Timestamptz>`.
        ///
        /// (Automatically generated by Diesel.)
        deleted_at -> Nullable<Timestamptz>,
    }
}

diesel::table! {
    /// Representation of the `workflow_triggers` table.
    ///
    /// (Automatically generated by Diesel.)
    workflow_triggers (id) {
        /// The `id` column of the `workflow_triggers` table.
        ///
        /// Its SQL type is `Uuid`.
        ///
        /// (Automatically generated by Diesel.)
        id -> Uuid,
        /// The `state_id` column of the `workflow_triggers` table.
        ///
        /// Its SQL type is `Uuid`.
        ///
        /// (Automatically generated by Diesel.)
        state_id -> Uuid,
        /// The `name` column of the `workflow_triggers` table.
        ///
        /// Its SQL type is `Varchar`.
        ///
        /// (Automatically generated by Diesel.)
        #[max_length = 255]
        name -> Varchar,
        /// The `description` column of the `workflow_triggers` table.
        ///
        /// Its SQL type is `Nullable<Text>`.
        ///
        /// (Automatically generated by Diesel.)
        description -> Nullable<Text>,
        /// The `configuration` column of the `workflow_triggers` table.
        ///
        /// Its SQL type is `Nullable<Jsonb>`.
        ///
        /// (Automatically generated by Diesel.)
        configuration -> Nullable<Jsonb>,
        /// The `created_at` column of the `workflow_triggers` table.
        ///
        /// Its SQL type is `Timestamptz`.
        ///
        /// (Automatically generated by Diesel.)
        created_at -> Timestamptz,
        /// The `updated_at` column of the `workflow_triggers` table.
        ///
        /// Its SQL type is `Timestamptz`.
        ///
        /// (Automatically generated by Diesel.)
        updated_at -> Timestamptz,
        /// The `deleted_at` column of the `workflow_triggers` table.
        ///
        /// Its SQL type is `Nullable<Timestamptz>`.
        ///
        /// (Automatically generated by Diesel.)
        deleted_at -> Nullable<Timestamptz>,
    }
}

diesel::table! {
    /// Representation of the `workflows` table.
    ///
    /// (Automatically generated by Diesel.)
    workflows (id) {
        /// The `id` column of the `workflows` table.
        ///
        /// Its SQL type is `Uuid`.
        ///
        /// (Automatically generated by Diesel.)
        id -> Uuid,
        /// The `tenant_id` column of the `workflows` table.
        ///
        /// Its SQL type is `Int4`.
        ///
        /// (Automatically generated by Diesel.)
        tenant_id -> Int4,
        /// The `name` column of the `workflows` table.
        ///
        /// Its SQL type is `Varchar`.
        ///
        /// (Automatically generated by Diesel.)
        #[max_length = 255]
        name -> Varchar,
        /// The `description` column of the `workflows` table.
        ///
        /// Its SQL type is `Nullable<Text>`.
        ///
        /// (Automatically generated by Diesel.)
        description -> Nullable<Text>,
        /// The `created_at` column of the `workflows` table.
        ///
        /// Its SQL type is `Timestamptz`.
        ///
        /// (Automatically generated by Diesel.)
        created_at -> Timestamptz,
        /// The `updated_at` column of the `workflows` table.
        ///
        /// Its SQL type is `Timestamptz`.
        ///
        /// (Automatically generated by Diesel.)
        updated_at -> Timestamptz,
        /// The `deleted_at` column of the `workflows` table.
        ///
        /// Its SQL type is `Nullable<Timestamptz>`.
        ///
        /// (Automatically generated by Diesel.)
        deleted_at -> Nullable<Timestamptz>,
        /// The `initial_state_id` column of the `workflows` table.
        ///
        /// Its SQL type is `Nullable<Uuid>`.
        ///
        /// (Automatically generated by Diesel.)
        initial_state_id -> Nullable<Uuid>,
    }
}

diesel::joinable!(users -> tenants (tenant_id));
diesel::joinable!(workflow_actions -> workflow_states (state_id));
diesel::joinable!(workflow_triggers -> workflow_states (state_id));
diesel::joinable!(workflows -> tenants (tenant_id));

diesel::allow_tables_to_appear_in_same_query!(
    tenants,
    users,
    workflow_actions,
    workflow_states,
    workflow_triggers,
    workflows,
);
